### ISSUE TITLE
Add action.yml for providing github annotiations

### ISSUE THREAD

**Issue by chee** [Financial-Times/remark-preset-lint-origami-component#5]
i thought that this problem matcher:

```json
{
	"problemMatcher": [{
		"owner": "remark-lint",
		"pattern": [
			{
				"regexp": "^([^\\s].*)$",
				"file": 1
			},
			{
				"regexp": "^\\s+(\\d+):(\\d+)-(\\d+):(\\d+)\\s+(error|warning|info)\\s+(.*)\\s\\s+(.*)$",
				"line": 1,
				"column": 2,
				"endLine": 3,
				"endColumn": 4,
				"severity": 5,
				"message": 6,
				"code": 7,
				"loop": true
			}
		]
	}]
}
```

and this action:

```yml
name: remark lint
on: [push]
jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set node.js 14.x
      uses: actions/setup-node@master
      with:
        version: 14.x
    - name: npm install
      run: npm install
    - name: install remark-cli
      run: npm install -g remark-cli
    - name: add matcher
      run: echo '##[add-matcher].github/remark-lint-problem-matcher.json'
    - name: lint readme
      run: npx remark-cli -f README.md > /dev/null
```

would give us github annotations, but they didn't.

some time let's add ones that work
